export const postsData = [{
    "uid": "dsadhaudhuaish",
    "username": "server",
    "profilepicture": " https://m.media-amazon.com/images/I/51ufsmqJmyL._AC_UL320_.jpg",
    "image": "https://m.media-amazon.com/images/I/51ufsmqJmyL._AC_UL320_.jpg",
    "profilepicuture": "https://m.media-amazon.com/images/I/51ufsmqJmyL._AC_UL320_.jpg",
    "desc": "Biggest nerd",
    "comments": "1cjahdjkas",
    "likes": "1",
  }, {
    "uid": "dsadhaudhuaish",
    "username": "server",
    "profilepicture": " https://m.media-amazon.com/images/I/51ufsmqJmyL._AC_UL320_.jpg",
    "image": "https://m.media-amazon.com/images/I/51ufsmqJmyL._AC_UL320_.jpg",
    "profilepicuture": "https://m.media-amazon.com/images/I/51ufsmqJmyL._AC_UL320_.jpg",
    "desc": "CEO",
    "comments": "1",
    "likes": "1",
  },{
    "uid": "dsadhaudhuaish",
    "username": "server",
    "profilepicture": " https://m.media-amazon.com/images/I/51ufsmqJmyL._AC_UL320_.jpg",
    "image": "https://m.media-amazon.com/images/I/51ufsmqJmyL._AC_UL320_.jpg",
    "profilepicuture": "https://m.media-amazon.com/images/I/51ufsmqJmyL._AC_UL320_.jpg",
    "desc": "CEO",
    "comments": "1",
    "likes": "1",
  }]